[package]
name = "advent_of_code"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
crossterm = "0.25.0"
lazy_static = "1.4.0"
nom = "7.1.1"
pathfinding = "4.0.0"
regex = "1.7.0"
